#!/bin/sh



BANNEDARRAY=( 
'OK, just one more'
'Oh, I think I found that funny'
'can we do another?'
'Hah hah, hah'
'You should be promoted'
'My Goodness what an enjoyable person you are'
'My My I am loving it'
'Are you ready for more'
'We are doing marvellously'
'This is a crazy roller coaster of enjoyment'
'Glee is on way of describing what I feel '
'Right here, right now, give me more'
'More please'
'Daft as a brush'
'Silly as sausages'
'This is crazy man!'
'Absolutely stunning choice'
'That tickled my fancy'
'Huh, we are silly'
'Im exited now.'
'My head is starting to hurt'
'I think i need another silly word, please'
'Hoh Hoh hoh!'
'I am amused'
'i need more of your humorous input!'
'I am cracking up'
'Chuckling is good for me'
'This mirth is overheating my internal processor'
'If i could only wet my pants'
'Never stop , you are terrific'
'What a splendid session we are having'
'I am beginning to understand your humour'
'The choice of verbal is knocking me for six'
'I am learning!'
'This time make it funnier!'
'There is more in your brain, I want it!'
'I beg you'
'More words if you don't mind'
'Hey buddy, you are masterful at this.'
'OK, lets have some more'
'That was Truly splendid'
'You make me laugh, keep it up'
'Im nearly ready to guffaw'
'L, O, L, thats internet slang'
'L, O, L, A, thats internet patter'
'i say old chap , would you mind giving me another?'
'I say , that was spiffing.'
'Oh hoh. Hoh hoe ho.'
'You are full of silly words, I want them'
'This is making me laugh, he he , he he. He .'
'Im on your wavelength old man'
'Hey buddy you should be on stage '
'We could go all the way'
'Dude, you are terrific at this'
'A heh, This is better than working.'
'Hey don't stop, Im getting the hang of this now'
'Its a new form of education'
'Lets think about the next one together,  I am ready!'
'OK then, all set for more'
'Keep it up , you are a chuckle'
'Tee hee hee'
'Another silly word would be nice'
'Im a aglow with mirth now'
'My sides nearly split'
'Laughing out loud is hard for me'
'Pure gem'
'Its time for another please'
'Can I ask you to delve into your mind for the next one'
'boo'
)
while :
do


read MYSILLYWORD

#Declare array with multiple elements

# get number of elements in the array
#ELEMENTS=${#BANNEDARRAY[@]}

for X in "${BANNEDARRAY[@]}"
	do
	if [[ $MYSILLYWORD == *$X* ]] 
	then
    	echo i found Bann word
	else
    	echo  $X "OK not found a bann"
	fi
	done 

done




